"use client";
import * as React from "react";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { useIsMobile } from "@/hooks/use-mobile";
const SIDEBAR_COOKIE_NAME = "sidebar_state";
type SidebarContextValue = { open: boolean; setOpen: (open: boolean) => void; isMobile: boolean; toggleSidebar: () => void };
const SidebarContext = React.createContext<SidebarContextValue | null>(null);
function useSidebar() { const context = React.useContext(SidebarContext); if (!context) throw new Error("useSidebar must be used within a SidebarProvider."); return context; }
function SidebarProvider({ defaultOpen = true, open: openProp, onOpenChange, className, style, children, ...props }: React.ComponentProps<"div"> & { defaultOpen?: boolean; open?: boolean; onOpenChange?: (open: boolean) => void }) { const isMobile = useIsMobile(); const [_open, _setOpen] = React.useState(defaultOpen); const open = openProp ?? _open; const setOpen = React.useCallback((value: boolean) => { if (onOpenChange) onOpenChange(value); else _setOpen(value); document.cookie = `${SIDEBAR_COOKIE_NAME}=${value}; path=/; max-age=604800`; }, [onOpenChange]); const toggleSidebar = React.useCallback(() => setOpen(!open), [open, setOpen]); const contextValue = React.useMemo(() => ({ open, setOpen, isMobile, toggleSidebar }), [open, setOpen, isMobile, toggleSidebar]); return <SidebarContext.Provider value={contextValue}><div data-slot="sidebar-wrapper" style={style} className={cn("group/sidebar-wrapper has-data-[variant=inset]:bg-sidebar flex min-h-svh w-full", className)} {...props}>{children}</div></SidebarContext.Provider>; }
function Sidebar({ className, side = "left", variant = "sidebar", collapsible = "offcanvas", ...props }: React.ComponentProps<"div"> & { side?: "left" | "right"; variant?: "sidebar" | "floating" | "inset"; collapsible?: "offcanvas" | "icon" | "none" }) { return <div data-slot="sidebar" data-side={side} data-variant={variant} data-collapsible={collapsible} className={cn("bg-sidebar text-sidebar-foreground flex h-svh w-64 flex-col border-r", className)} {...props} />; }
function SidebarTrigger({ className, onClick, ...props }: React.ComponentProps<typeof Button>) { const { toggleSidebar } = useSidebar(); return <Button data-slot="sidebar-trigger" variant="ghost" size="icon" className={cn("size-7", className)} onClick={(event) => { onClick?.(event); toggleSidebar(); }} {...props}><span className="sr-only">Toggle Sidebar</span>☰</Button>; }
function SidebarContent({ className, ...props }: React.ComponentProps<"div">) { return <div data-slot="sidebar-content" className={cn("flex min-h-0 flex-1 flex-col gap-2 overflow-auto p-2", className)} {...props} />; }
function SidebarHeader({ className, ...props }: React.ComponentProps<"div">) { return <div data-slot="sidebar-header" className={cn("flex flex-col gap-2 p-2", className)} {...props} />; }
function SidebarFooter({ className, ...props }: React.ComponentProps<"div">) { return <div data-slot="sidebar-footer" className={cn("flex flex-col gap-2 p-2", className)} {...props} />; }
function SidebarGroup({ className, ...props }: React.ComponentProps<"div">) { return <div data-slot="sidebar-group" className={cn("relative flex w-full min-w-0 flex-col p-2", className)} {...props} />; }
function SidebarGroupLabel({ className, ...props }: React.ComponentProps<"div">) { return <div data-slot="sidebar-group-label" className={cn("text-sidebar-foreground/70 flex h-8 shrink-0 items-center rounded-md px-2 text-xs font-medium", className)} {...props} />; }
function SidebarMenu({ className, ...props }: React.ComponentProps<"ul">) { return <ul data-slot="sidebar-menu" className={cn("flex w-full min-w-0 flex-col gap-1", className)} {...props} />; }
function SidebarMenuItem({ className, ...props }: React.ComponentProps<"li">) { return <li data-slot="sidebar-menu-item" className={cn("group/menu-item relative", className)} {...props} />; }
function SidebarMenuButton({ className, asChild = false, ...props }: React.ComponentProps<typeof Button> & { asChild?: boolean }) { return <Button data-slot="sidebar-menu-button" asChild={asChild} variant="ghost" className={cn("w-full justify-start text-sidebar-foreground hover:bg-sidebar-accent hover:text-sidebar-accent-foreground", className)} {...props} />; }
function SidebarInset({ className, ...props }: React.ComponentProps<"main">) { return <main data-slot="sidebar-inset" className={cn("bg-background relative flex w-full flex-1 flex-col", className)} {...props} />; }
export { Sidebar, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider, SidebarTrigger, useSidebar };
